"""Add open_time, end_time, speaker_bio to Seminar

Revision ID: 69fd14018937
Revises: 
Create Date: 2025-09-02 22:51:50.296789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fd14018937'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('seminar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('speaker_bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seminar', schema=None) as batch_op:
        batch_op.drop_column('speaker_bio')
        batch_op.drop_column('end_time')
        batch_op.drop_column('open_time')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
