"""venue_text

Revision ID: 979bc4d4bcc9
Revises: 69fd14018937
Create Date: 2025-09-02 23:32:25.444965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979bc4d4bcc9'
down_revision = '69fd14018937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seminar', schema=None) as batch_op:
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seminar', schema=None) as batch_op:
        batch_op.alter_column('venue',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
