"""注文管理機能用テーブル Orderer, Menu の追加

Revision ID: 9b5e726d3039
Revises: 979bc4d4bcc9
Create Date: 2025-09-04 10:37:26.098910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5e726d3039'
down_revision = '979bc4d4bcc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_excl_tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('menu_items')
    with op.batch_alter_table('orderers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_5', sa.String(length=100), nullable=True))
        batch_op.drop_column('item1')
        batch_op.drop_column('item5')
        batch_op.drop_column('item4')
        batch_op.drop_column('item2')
        batch_op.drop_column('item3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item3', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item4', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item5', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item1', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('item_5')
        batch_op.drop_column('item_4')
        batch_op.drop_column('item_3')
        batch_op.drop_column('item_2')
        batch_op.drop_column('item_1')

    op.create_table('menu_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price_excl_tax', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('menu_items_pkey'))
    )
    op.drop_table('menus')
    # ### end Alembic commands ###
