"""Add image_url column to Menu table

Revision ID: ed8f7e867ad3
Revises: 9b5e726d3039
Create Date: 2025-09-05 13:16:14.268165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8f7e867ad3'
down_revision = '9b5e726d3039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
